name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 56.124.101.132          
          username: ubuntu           
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "/var/www/html"

      - name: Reiniciar Apache
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 56.124.101.132
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo systemctl restart apache2
